name = "metamethods/store"
version = "0.1.0"
description = "A simple DataStore library for Roblox"
authors = ["metamethods"]
repository = "https://github.com/metamethods/store"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.1", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
Future = { name = "lukadev_0/future", version = "^1.0.2" }
Signal = { name = "jiwonz/signal", version = "^0.1.0" }
